name: 기능 추가
description: 새로운 기능이나 작업 내용을 작성합니다
title: "[FEAT] "
labels: ["feature"]
body:
  - type: textarea
    id: reason
    attributes:
      label: ✨ 어떤 기능인가요?
      description: 어떤 기능을 추가하려는지 적어주세요
      placeholder: 예) 수준 진단 시작 화면 UI 구현
    validations:
      required: true

  - type: textarea
    id: change
    attributes:
      label: 🛠️ 어떤 내용이 바뀌나요?
      description: 주요 작업 내용을 적어주세요
      placeholder: |
        - 시작 화면 UI 제작
        - 버튼 클릭 시 다음 화면 이동
        - 기본 문구 추가
    validations:
      required: false

  - type: textarea
    id: note
    attributes:
      label: 🙏 참고할 내용
      description: 팀원이나 리뷰어가 알면 좋은 내용을 적어주세요
      placeholder: 예) 피그마 시안 기준으로 작업 예정
    validations:
      required: false
